/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Principal;

/**
 *
 * @author José Luis López
 */
public class Perfil_Vip extends javax.swing.JFrame {

    /**
     * Creates new form Perfil_Vip
     */
    public Perfil_Vip() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AC_V = new javax.swing.JButton();
        S_V = new javax.swing.JButton();
        PV_1 = new javax.swing.JButton();
        PV_2 = new javax.swing.JButton();
        PV_3 = new javax.swing.JButton();
        PV_4 = new javax.swing.JButton();
        PV_5 = new javax.swing.JButton();
        Perfil = new javax.swing.JLabel();
        Perfil_2 = new javax.swing.JLabel();
        Perfil_3 = new javax.swing.JLabel();
        Perfil_4 = new javax.swing.JLabel();
        Perfil_5 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AC_V.setBackground(new java.awt.Color(0, 0, 0));
        AC_V.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        AC_V.setForeground(new java.awt.Color(255, 255, 255));
        AC_V.setText("Administrar cuenta");
        AC_V.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(AC_V, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 600, -1, -1));

        S_V.setBackground(new java.awt.Color(0, 0, 0));
        S_V.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        S_V.setForeground(new java.awt.Color(255, 255, 255));
        S_V.setText("Salir");
        S_V.setBorder(null);
        getContentPane().add(S_V, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 660, -1, -1));

        PV_1.setBackground(new java.awt.Color(0, 0, 0, 0));
        PV_1.setBorder(null);
        PV_1.setContentAreaFilled(false);
        getContentPane().add(PV_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 150, 150));

        PV_2.setBackground(new java.awt.Color(0, 0, 0, 0));
        PV_2.setBorder(null);
        PV_2.setContentAreaFilled(false);
        getContentPane().add(PV_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 150, 150));

        PV_3.setBackground(new java.awt.Color(0, 0, 0, 0));
        PV_3.setBorder(null);
        PV_3.setContentAreaFilled(false);
        getContentPane().add(PV_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 150, 150));

        PV_4.setBackground(new java.awt.Color(0, 0, 0, 0));
        PV_4.setBorder(null);
        PV_4.setContentAreaFilled(false);
        PV_4.setOpaque(false);
        getContentPane().add(PV_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, 140, 150));

        PV_5.setBackground(new java.awt.Color(0, 0, 0, 0));
        PV_5.setBorder(null);
        PV_5.setContentAreaFilled(false);
        PV_5.setOpaque(false);
        getContentPane().add(PV_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 300, 160, 170));

        Perfil.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Perfil.setForeground(new java.awt.Color(255, 255, 255));
        Perfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 150, 35));

        Perfil_2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Perfil_2.setForeground(new java.awt.Color(255, 255, 255));
        Perfil_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Perfil_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 150, 35));

        Perfil_3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Perfil_3.setForeground(new java.awt.Color(255, 255, 255));
        Perfil_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Perfil_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 150, 35));

        Perfil_4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Perfil_4.setForeground(new java.awt.Color(255, 255, 255));
        Perfil_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Perfil_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, 150, 35));

        Perfil_5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Perfil_5.setForeground(new java.awt.Color(255, 255, 255));
        Perfil_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Perfil_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 480, 150, 35));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/VIP.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil_Vip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil_Vip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil_Vip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil_Vip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil_Vip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AC_V;
    public javax.swing.JButton PV_1;
    public javax.swing.JButton PV_2;
    public javax.swing.JButton PV_3;
    public javax.swing.JButton PV_4;
    public javax.swing.JButton PV_5;
    public javax.swing.JLabel Perfil;
    public javax.swing.JLabel Perfil_2;
    public javax.swing.JLabel Perfil_3;
    public javax.swing.JLabel Perfil_4;
    public javax.swing.JLabel Perfil_5;
    public javax.swing.JButton S_V;
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables
}
