/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Principal;

/**
 *
 * @author José Luis López
 */
public class Perfil_Premium extends javax.swing.JFrame {

    /**
     * Creates new form Perfil_Premium
     */
    public Perfil_Premium() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Perfil_1 = new javax.swing.JLabel();
        Perfil_2 = new javax.swing.JLabel();
        Perfil_3 = new javax.swing.JLabel();
        PP = new javax.swing.JButton();
        PP_2 = new javax.swing.JButton();
        PP_3 = new javax.swing.JButton();
        AC_P = new javax.swing.JButton();
        S_P = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Perfil_1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Perfil_1.setForeground(new java.awt.Color(255, 255, 255));
        Perfil_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Perfil_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 150, 35));

        Perfil_2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Perfil_2.setForeground(new java.awt.Color(255, 255, 255));
        Perfil_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Perfil_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 150, 35));

        Perfil_3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Perfil_3.setForeground(new java.awt.Color(255, 255, 255));
        Perfil_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Perfil_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, 150, 35));

        PP.setBackground(new java.awt.Color(0, 0, 0, 0));
        PP.setBorder(null);
        PP.setContentAreaFilled(false);
        getContentPane().add(PP, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 150, 150));

        PP_2.setBackground(new java.awt.Color(0, 0, 0, 0));
        PP_2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PP_2.setContentAreaFilled(false);
        getContentPane().add(PP_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 150, 150));

        PP_3.setBackground(new java.awt.Color(0, 0, 0, 0));
        PP_3.setBorder(null);
        PP_3.setContentAreaFilled(false);
        getContentPane().add(PP_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, 140, 150));

        AC_P.setBackground(new java.awt.Color(0, 0, 0));
        AC_P.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        AC_P.setForeground(new java.awt.Color(255, 255, 255));
        AC_P.setText("Administrar cuenta");
        AC_P.setBorder(null);
        getContentPane().add(AC_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 580, -1, -1));

        S_P.setBackground(new java.awt.Color(0, 0, 0));
        S_P.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        S_P.setForeground(new java.awt.Color(255, 255, 255));
        S_P.setText("Salir");
        S_P.setBorder(null);
        getContentPane().add(S_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 640, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Premium.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1368, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static void main(String args[]) {
    /**
     * @param args the command line arguments
   fondo  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced fondo SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil_Premium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil_Premium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil_Premium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil_Premium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil_Premium().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AC_P;
    public javax.swing.JButton PP;
    public javax.swing.JButton PP_2;
    public javax.swing.JButton PP_3;
    public javax.swing.JLabel Perfil_1;
    public javax.swing.JLabel Perfil_2;
    public javax.swing.JLabel Perfil_3;
    public javax.swing.JButton S_P;
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables
}
