/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Principal;

/**
 *
 * @author José Luis López
 */
public class Perfil_Gold extends javax.swing.JFrame {

    /**
     * Creates new form Perfil_Gold
     */
    public Perfil_Gold() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Perfil_1 = new javax.swing.JLabel();
        Perfil_2 = new javax.swing.JLabel();
        PG_1 = new javax.swing.JButton();
        PG_2 = new javax.swing.JButton();
        AC_G = new javax.swing.JButton();
        S_G = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Perfil_1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Perfil_1.setForeground(new java.awt.Color(255, 255, 255));
        Perfil_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Perfil_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 150, 35));

        Perfil_2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Perfil_2.setForeground(new java.awt.Color(255, 255, 255));
        Perfil_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Perfil_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, 150, 35));

        PG_1.setBackground(new java.awt.Color(0, 0, 0, 0));
        PG_1.setBorder(null);
        PG_1.setContentAreaFilled(false);
        getContentPane().add(PG_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 160, 160));

        PG_2.setBackground(new java.awt.Color(0, 0, 0, 0));
        PG_2.setBorder(null);
        PG_2.setContentAreaFilled(false);
        getContentPane().add(PG_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 150, 160));

        AC_G.setBackground(new java.awt.Color(0, 0, 0));
        AC_G.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        AC_G.setForeground(new java.awt.Color(255, 255, 255));
        AC_G.setText("Administrar cuenta");
        AC_G.setBorder(null);
        getContentPane().add(AC_G, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 580, -1, -1));

        S_G.setBackground(new java.awt.Color(0, 0, 0));
        S_G.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        S_G.setForeground(new java.awt.Color(255, 255, 255));
        S_G.setText("Salir");
        S_G.setBorder(null);
        getContentPane().add(S_G, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 650, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Gold.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil_Gold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil_Gold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil_Gold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil_Gold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil_Gold().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AC_G;
    public javax.swing.JButton PG_1;
    public javax.swing.JButton PG_2;
    public javax.swing.JLabel Perfil_1;
    public javax.swing.JLabel Perfil_2;
    public javax.swing.JButton S_G;
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables
}
