/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Usuario;

/**
 *
 * @author PC
 */
public class Usuario_Actualizar extends javax.swing.JFrame {

    /**
     * Creates new form Usuario_Actualizar
     */
    public Usuario_Actualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        Primer_Nombre = new javax.swing.JTextField();
        primer_apell = new javax.swing.JLabel();
        Primer_Apellido = new javax.swing.JTextField();
        Fecha_Dos = new javax.swing.JLabel();
        dia = new javax.swing.JTextField();
        mes = new javax.swing.JTextField();
        año = new javax.swing.JTextField();
        Pais = new javax.swing.JComboBox<>();
        Pais_2 = new javax.swing.JLabel();
        Genero = new javax.swing.JComboBox<>();
        genero_ = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Informacion_Personal1 = new javax.swing.JLabel();
        Informacion_Personal = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Nro_Tarjeta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        contraseña = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 700));
        setPreferredSize(new java.awt.Dimension(1050, 700));
        getContentPane().setLayout(null);

        usuario.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(usuario);
        usuario.setBounds(190, 340, 210, 30);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel1.setText("Username:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 340, 80, 30);

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel2.setText("Correo electronico:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 380, 130, 30);

        correo.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(correo);
        correo.setBounds(190, 380, 210, 30);

        Nombre.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Nombre.setText("Primer nombre:");
        getContentPane().add(Nombre);
        Nombre.setBounds(80, 100, 110, 30);

        Primer_Nombre.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Primer_Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Primer_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Primer_NombreActionPerformed(evt);
            }
        });
        getContentPane().add(Primer_Nombre);
        Primer_Nombre.setBounds(190, 100, 210, 30);

        primer_apell.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        primer_apell.setText("Primer apellido:");
        getContentPane().add(primer_apell);
        primer_apell.setBounds(80, 140, 110, 28);

        Primer_Apellido.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Primer_Apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Primer_Apellido);
        Primer_Apellido.setBounds(190, 140, 210, 30);

        Fecha_Dos.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Fecha_Dos.setText("Fecha de nacimiento:");
        getContentPane().add(Fecha_Dos);
        Fecha_Dos.setBounds(50, 180, 140, 30);

        dia.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        dia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dia.setText("DD");
        getContentPane().add(dia);
        dia.setBounds(190, 180, 65, 30);

        mes.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        mes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mes.setText("MM");
        getContentPane().add(mes);
        mes.setBounds(260, 180, 65, 30);

        año.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        año.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        año.setText("AAAA");
        getContentPane().add(año);
        año.setBounds(330, 180, 70, 30);

        Pais.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Pais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Canada", "Estados Unidos", "Italia ", "Japon", "Venezuela " }));
        Pais.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaisActionPerformed(evt);
            }
        });
        getContentPane().add(Pais);
        Pais.setBounds(190, 220, 210, 30);

        Pais_2.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Pais_2.setText("Pais:");
        getContentPane().add(Pais_2);
        Pais_2.setBounds(146, 220, 40, 30);

        Genero.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        Genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Femenino", "Masculino", "Desconocido", "Otros" }));
        getContentPane().add(Genero);
        Genero.setBounds(190, 260, 210, 30);

        genero_.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        genero_.setText("Genero:");
        getContentPane().add(genero_);
        genero_.setBounds(130, 260, 49, 30);

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel10.setText("USUARIO");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(210, 30, 110, 30);

        Informacion_Personal1.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        Informacion_Personal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Informacion_Personal1.setText("Informacion personal");
        getContentPane().add(Informacion_Personal1);
        Informacion_Personal1.setBounds(40, 70, 180, 17);

        Informacion_Personal.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        Informacion_Personal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Informacion_Personal.setText("Informacion usuario");
        getContentPane().add(Informacion_Personal);
        Informacion_Personal.setBounds(40, 310, 180, 17);

        Regresar.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar);
        Regresar.setBounds(40, 530, 180, 35);

        Actualizar.setBackground(new java.awt.Color(153, 204, 255));
        Actualizar.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(Actualizar);
        Actualizar.setBounds(230, 530, 180, 35);

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel3.setText("Numero de tarjeta:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 480, 120, 16);
        getContentPane().add(Nro_Tarjeta);
        Nro_Tarjeta.setBounds(190, 470, 210, 30);

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 430, 90, 15);
        getContentPane().add(contraseña);
        contraseña.setBounds(190, 420, 210, 30);

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Login Cruds.png"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(1040, 680));
        jLabel8.setMinimumSize(new java.awt.Dimension(1040, 680));
        jLabel8.setPreferredSize(new java.awt.Dimension(1040, 680));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1040, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaisActionPerformed

    private void Primer_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Primer_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Primer_NombreActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegresarActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario_Actualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Actualizar;
    private javax.swing.JLabel Fecha_Dos;
    public javax.swing.JComboBox<String> Genero;
    private javax.swing.JLabel Informacion_Personal;
    private javax.swing.JLabel Informacion_Personal1;
    private javax.swing.JLabel Nombre;
    public javax.swing.JTextField Nro_Tarjeta;
    public javax.swing.JComboBox<String> Pais;
    private javax.swing.JLabel Pais_2;
    public javax.swing.JTextField Primer_Apellido;
    public javax.swing.JTextField Primer_Nombre;
    public javax.swing.JButton Regresar;
    public javax.swing.JTextField año;
    public javax.swing.JTextField contraseña;
    public javax.swing.JTextField correo;
    public javax.swing.JTextField dia;
    private javax.swing.JLabel genero_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JTextField mes;
    private javax.swing.JLabel primer_apell;
    public javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
