/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JTextField;

/**
 *
 * @author José Luis López
 */
public class Registrar_Usuario_Dos extends javax.swing.JFrame {

    /**
     * Creates new form Registrar_Usuario_Dos
     */
    public Registrar_Usuario_Dos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Regresar = new javax.swing.JButton();
        Registrar = new javax.swing.JButton();
        Primer_Nombre = new javax.swing.JTextField();
        Segundo_Nombre = new javax.swing.JTextField();
        Primer_Apellido = new javax.swing.JTextField();
        Segundo_Apellido = new javax.swing.JTextField();
        dia = new javax.swing.JTextField();
        año = new javax.swing.JTextField();
        mes = new javax.swing.JTextField();
        Pais = new javax.swing.JComboBox<>();
        Genero = new javax.swing.JComboBox<>();
        Fecha_Dos = new javax.swing.JLabel();
        Pais_2 = new javax.swing.JLabel();
        primer_apell = new javax.swing.JLabel();
        segundo_apell = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        genero_ = new javax.swing.JLabel();
        Obligatorio = new javax.swing.JLabel();
        Obligatorio1 = new javax.swing.JLabel();
        Obligatorio2 = new javax.swing.JLabel();
        Obligatorio3 = new javax.swing.JLabel();
        Informacion_Personal = new javax.swing.JLabel();
        Obligatorio5 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Obligatorio4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1370, 770));
        setPreferredSize(new java.awt.Dimension(1370, 770));
        getContentPane().setLayout(null);

        Regresar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Regresar.setText("Regresar\n");
        getContentPane().add(Regresar);
        Regresar.setBounds(150, 550, 150, 35);

        Registrar.setBackground(new java.awt.Color(46, 199, 62));
        Registrar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Registrar.setText("Continuar");
        getContentPane().add(Registrar);
        Registrar.setBounds(340, 550, 150, 35);

        Primer_Nombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Primer_Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Primer_Nombre);
        Primer_Nombre.setBounds(90, 210, 210, 35);

        Segundo_Nombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Segundo_Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Segundo_Nombre);
        Segundo_Nombre.setBounds(340, 210, 210, 35);

        Primer_Apellido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Primer_Apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Primer_Apellido);
        Primer_Apellido.setBounds(90, 300, 210, 35);

        Segundo_Apellido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Segundo_Apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Segundo_Apellido);
        Segundo_Apellido.setBounds(340, 300, 210, 35);

        dia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dia.setText("DD");
        getContentPane().add(dia);
        dia.setBounds(90, 390, 60, 35);

        año.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        año.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        año.setText("AAAA");
        getContentPane().add(año);
        año.setBounds(240, 390, 60, 35);

        mes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mes.setText("MM");
        getContentPane().add(mes);
        mes.setBounds(170, 390, 60, 35);

        Pais.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Pais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Canada", "Estados Unidos", "Italia ", "Japon", "Venezuela " }));
        Pais.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaisActionPerformed(evt);
            }
        });
        getContentPane().add(Pais);
        Pais.setBounds(340, 390, 210, 35);

        Genero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Femenino", "Masculino", "Desconocido", "Otros" }));
        getContentPane().add(Genero);
        Genero.setBounds(210, 490, 210, 35);

        Fecha_Dos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Fecha_Dos.setForeground(new java.awt.Color(255, 255, 255));
        Fecha_Dos.setText("Fecha de nacimiento:");
        getContentPane().add(Fecha_Dos);
        Fecha_Dos.setBounds(90, 360, 170, 22);

        Pais_2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Pais_2.setForeground(new java.awt.Color(255, 255, 255));
        Pais_2.setText("Pais");
        getContentPane().add(Pais_2);
        Pais_2.setBounds(340, 360, 50, 22);

        primer_apell.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        primer_apell.setForeground(new java.awt.Color(255, 255, 255));
        primer_apell.setText("Primer apellido:");
        getContentPane().add(primer_apell);
        primer_apell.setBounds(90, 270, 150, 28);

        segundo_apell.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        segundo_apell.setForeground(new java.awt.Color(255, 255, 255));
        segundo_apell.setText("Segundo apellido:");
        getContentPane().add(segundo_apell);
        segundo_apell.setBounds(340, 262, 150, 30);

        Nombre.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Primer nombre:");
        getContentPane().add(Nombre);
        Nombre.setBounds(100, 180, 130, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Segundo nombre:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 180, 140, 30);

        genero_.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        genero_.setForeground(new java.awt.Color(255, 255, 255));
        genero_.setText("Genero");
        getContentPane().add(genero_);
        genero_.setBounds(280, 460, 70, 20);

        Obligatorio.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        Obligatorio.setForeground(new java.awt.Color(255, 0, 51));
        Obligatorio.setText("*");
        getContentPane().add(Obligatorio);
        Obligatorio.setBounds(220, 170, 10, 15);

        Obligatorio1.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        Obligatorio1.setForeground(new java.awt.Color(255, 0, 51));
        Obligatorio1.setText("*");
        getContentPane().add(Obligatorio1);
        Obligatorio1.setBounds(210, 270, 20, 15);

        Obligatorio2.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        Obligatorio2.setForeground(new java.awt.Color(255, 0, 51));
        Obligatorio2.setText("*");
        getContentPane().add(Obligatorio2);
        Obligatorio2.setBounds(250, 350, 20, 20);

        Obligatorio3.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        Obligatorio3.setForeground(new java.awt.Color(255, 0, 51));
        Obligatorio3.setText("*");
        getContentPane().add(Obligatorio3);
        Obligatorio3.setBounds(340, 450, 26, 20);

        Informacion_Personal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Informacion_Personal.setForeground(new java.awt.Color(255, 255, 255));
        Informacion_Personal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Informacion_Personal.setText("Informacion personal");
        getContentPane().add(Informacion_Personal);
        Informacion_Personal.setBounds(200, 110, 260, 40);

        Obligatorio5.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        Obligatorio5.setForeground(new java.awt.Color(255, 0, 51));
        Obligatorio5.setText("*");
        getContentPane().add(Obligatorio5);
        Obligatorio5.setBounds(370, 360, 26, 10);

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Registrar usuario");
        getContentPane().add(Titulo);
        Titulo.setBounds(150, 70, 350, 40);

        Obligatorio4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Obligatorio4.setForeground(new java.awt.Color(255, 255, 255));
        Obligatorio4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Registrase.jpg"))); // NOI18N
        getContentPane().add(Obligatorio4);
        Obligatorio4.setBounds(0, 0, 1370, 770);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(620, 120, 37, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_Usuario_Dos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_Usuario_Dos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_Usuario_Dos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_Usuario_Dos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar_Usuario_Dos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fecha_Dos;
    public javax.swing.JComboBox<String> Genero;
    private javax.swing.JLabel Informacion_Personal;
    private javax.swing.JLabel Nombre;
    public javax.swing.JLabel Obligatorio;
    public javax.swing.JLabel Obligatorio1;
    public javax.swing.JLabel Obligatorio2;
    public javax.swing.JLabel Obligatorio3;
    private javax.swing.JLabel Obligatorio4;
    private javax.swing.JLabel Obligatorio5;
    public javax.swing.JComboBox<String> Pais;
    private javax.swing.JLabel Pais_2;
    public javax.swing.JTextField Primer_Apellido;
    public javax.swing.JTextField Primer_Nombre;
    public javax.swing.JButton Registrar;
    public javax.swing.JButton Regresar;
    public javax.swing.JTextField Segundo_Apellido;
    public javax.swing.JTextField Segundo_Nombre;
    private javax.swing.JLabel Titulo;
    public javax.swing.JTextField año;
    public javax.swing.JTextField dia;
    private javax.swing.JLabel genero_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JTextField mes;
    private javax.swing.JLabel primer_apell;
    private javax.swing.JLabel segundo_apell;
    // End of variables declaration//GEN-END:variables

    /*public JTextField getFecha() {
        return fecha;
    }*/
}
